import { MessageSquare, FileText, CheckCircle, Users, Activity, Info } from 'lucide-react';

const KPICard = ({ title, value, icon: Icon, color, subValue, tooltip, tooltipPosition }) => (
    <div className="card" style={{
        padding: '24px',
        display: 'flex',
        flexDirection: 'column',
        gap: '12px',
        position: 'relative',
        minHeight: '140px'
    }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                <span style={{ fontSize: '12px', color: '#64748b', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.05em' }}>{title}</span>
                <div className="tooltip-trigger">
                    <Info size={14} color="#cbd5e1" />
                    <div className={`tooltip-content ${tooltipPosition || ''}`}>
                        {tooltip}
                    </div>
                </div>
            </div>
            <div style={{
                padding: '10px',
                borderRadius: '12px',
                backgroundColor: `${color}10`,
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center'
            }}>
                <Icon size={20} color={color} />
            </div>
        </div>
        <div>
            <div style={{ fontSize: '32px', fontWeight: 800, color: '#1e293b', lineHeight: 1 }}>{value}</div>
            {subValue && (
                <div style={{ display: 'flex', alignItems: 'center', gap: '6px', marginTop: '12px' }}>
                    <div style={{ width: '6px', height: '6px', borderRadius: '50%', backgroundColor: color }} />
                    <div style={{ fontSize: '11px', color: '#64748b', fontWeight: 600 }}>{subValue}</div>
                </div>
            )}
        </div>
    </div>
);

const KPIGrid = ({ analytics }) => {
    if (!analytics) return null;

    const { failed_conversations, plan_complexity, user_behavior, system_health } = analytics;

    return (
        <div style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(5, 1fr)',
            gap: '20px',
            marginBottom: '32px'
        }}>
            <KPICard
                title="Total Conversations"
                value={failed_conversations.total_conversations}
                icon={MessageSquare}
                color="#3b82f6"
                tooltip="The aggregate count of all user-system dialogue sessions recorded in this period."
                subValue="All time sessions"
                tooltipPosition="left"
            />
            <KPICard
                title="Total Plans"
                value={plan_complexity.total_plans}
                icon={FileText}
                color="#8b5cf6"
                tooltip="Number of execution plans generated by the agent to fulfill user requests."
                subValue="Unique execution paths"
            />
            <KPICard
                title="Success Rate"
                value={`${failed_conversations.success_rate}%`}
                icon={CheckCircle}
                color="#10b981"
                tooltip="The percentage of conversations that completed without technical errors or failures."
                subValue="Goal: >95%"
            />
            <KPICard
                title="Active Users"
                value={user_behavior.total_active_users}
                icon={Users}
                color="#f59e0b"
                tooltip="Unique users who interacted with the platform during the selected time window."
                subValue="Current session reach"
            />
            <KPICard
                title="System Health"
                value={system_health.overall_health.toUpperCase()}
                icon={Activity}
                color={system_health.overall_health === 'healthy' ? '#10b981' : '#ef4444'}
                tooltip="Real-time assessment of system stability based on SLOs, latency, and error rates."
                subValue={`${system_health.slo_summary.compliance_rate}% Compliance`}
                tooltipPosition="right"
            />
        </div>
    );
};

export default KPIGrid;
